# Generated by Django 5.1.7 on 2026-02-03 13:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academic_Subject',
            fields=[
                ('SubjectCode', models.CharField(max_length=50, primary_key=True, serialize=False, validators=[django.core.validators.MaxLengthValidator(50)])),
                ('SubjectName', models.CharField(max_length=255)),
                ('Semester', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('Branch', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'academic_subject',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Faculty_Teacher',
            fields=[
                ('TeacherID', models.CharField(max_length=50, primary_key=True, serialize=False, validators=[django.core.validators.MaxLengthValidator(50)], verbose_name='Teacher ID')),
                ('FullName', models.CharField(max_length=255)),
                ('Designation', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'faculty_teacher',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Users_Student',
            fields=[
                ('EnrollmentNo', models.CharField(max_length=50, primary_key=True, serialize=False, validators=[django.core.validators.MaxLengthValidator(50)])),
                ('FullName', models.CharField(max_length=255)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('Email', models.CharField(max_length=255, validators=[django.core.validators.EmailValidator()])),
                ('Branch', models.CharField(max_length=255)),
                ('Year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('Semester', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('Section', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('IsActive', models.BooleanField(default=True)),
                ('DateOfBirth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
            ],
            options={
                'db_table': 'users_student',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Academic_Allocation',
            fields=[
                ('AllocationID', models.AutoField(primary_key=True, serialize=False)),
                ('TargetBranch', models.CharField(max_length=50)),
                ('Target_Year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('Target_Semester', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('Target_Section', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('SubjectCode', models.ForeignKey(db_column='SubjectCode', on_delete=django.db.models.deletion.CASCADE, to='feedback_app.academic_subject')),
                ('TeacherID', models.ForeignKey(db_column='TeacherID', on_delete=django.db.models.deletion.CASCADE, to='feedback_app.faculty_teacher')),
            ],
            options={
                'db_table': 'academic_allocation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Feedback_Response',
            fields=[
                ('ResponseID', models.AutoField(primary_key=True, serialize=False)),
                ('Q1_Rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('Q2_Rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('Q3_Rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('Q4_Rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('Q5_Rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('Q6_Rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('Q7_Rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('Q8_Rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('Q9_Rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('Q10_Rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('Comments', models.CharField(blank=True, max_length=500, null=True, validators=[django.core.validators.MaxLengthValidator(500)])),
                ('AllocationID', models.ForeignKey(db_column='AllocationID', on_delete=django.db.models.deletion.CASCADE, to='feedback_app.academic_allocation')),
            ],
            options={
                'db_table': 'feedback_response',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Feedback_SubmissionLog',
            fields=[
                ('LogID', models.AutoField(primary_key=True, serialize=False)),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
                ('AllocationID', models.ForeignKey(db_column='AllocationID', on_delete=django.db.models.deletion.CASCADE, to='feedback_app.academic_allocation')),
                ('ResponseID', models.ForeignKey(db_column='ResponseID', on_delete=django.db.models.deletion.CASCADE, to='feedback_app.feedback_response')),
                ('EnrollmentNo', models.ForeignKey(db_column='EnrollmentNo', on_delete=django.db.models.deletion.CASCADE, to='feedback_app.users_student')),
            ],
            options={
                'db_table': 'feedback_submissionlog',
                'managed': True,
            },
        ),
    ]
